#!/usr/bin/python
# -*- coding: windows-1252 -*-

import wxversion
wxversion.select('2.8')
import wx

ID_CERRAR_APLICACION = wx.ID_EXIT

ID_CREAR_MODELO = wx.ID_NEW
ID_ABRIR_MODELO = wx.ID_OPEN
ID_GUARDAR_MODELO = wx.ID_SAVE
ID_GUARDAR_COMO_MODELO = wx.ID_SAVEAS
ID_EXPORTAR_MODELO = wx.NewId()

ID_MENU_VER_REFRESCAR = wx.NewId()
ID_MENU_VER_IDF1X = wx.NewId()
ID_MENU_VER_STANDARD = wx.NewId()
ID_MENU_VER_NAV = wx.NewId()
ID_MENU_VER_CARD = wx.NewId()
ID_MENU_VER_BARRA_ESTADO = wx.NewId()

ID_MENU_HELP_AYUDA = wx.ID_HELP
ID_MENU_HELP_LOG = wx.NewId()
ID_MENU_HELP_ACERCA_DE = wx.NewId()

ID_PUNTERO_MOUSE = wx.NewId()

ID_CREAR_ENTIDAD = wx.NewId()
ID_MODIFICAR_ENTIDAD = wx.NewId()
ID_ELIMINAR_ENTIDAD = wx.NewId()

ID_CREAR_ATRIBUTO = wx.NewId()
ID_MODIFICAR_ATRIBUTO = wx.NewId()
ID_ELIMINAR_ATRIBUTO = wx.NewId()
ID_TREE_MODIFICAR_ATRIBUTO = wx.NewId()
ID_TREE_ELIMINAR_ATRIBUTO = wx.NewId()

ID_CREAR_RELACION = wx.NewId()
ID_RELACION_IDENTIF = wx.NewId()
ID_RELACION_NO_IDENTIF = wx.NewId()
ID_MODIFICAR_RELACION = wx.NewId()
ID_ELIMINAR_RELACION = wx.NewId()

ID_GENERAR_SCRIPT= wx.NewId()

ID_TREE_FRAME = wx.NewId()